### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by runwithyourheart** [yhfeng1995/ORB-SLAM2_DENSE#1]
你好，想请教两个问题，你说的  修复Eigen固定维度数组内存对齐问题   ，请问这个问题你是怎么解决的，能分享下经验吗？还有如果不用RGB-D，用双目或单目建立一个类似的八叉树地图或栅格地图有没有可能实现呢？谢谢

**Comment by yhfeng1995** [comment]
第一个数组不对齐的问题主要出现在固定维度Eigen数组为自定义类中成员变量，或者为标准库容器/智能指针模板元素等情况，具体情况见https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html

第二个问题，理论上是可行的，但是实现不太容易，两者都需要稠密的深度度支持图像反投影为点云，双目的话需要立体匹配获得视差图，单目需要SfM估计深度。或者考虑使用硬件带立体匹配的双目摄像头，比如小觅。

**Comment by runwithyourheart** [comment]
> 第一个数组不对齐的问题主要出现在固定维度Eigen数组为自定义类中成员变量，或者为标准库容器/智能指针模板元素等情况，具体情况见https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html
> 
> 第二个问题，理论上是可行的，但是实现不太容易，两者都需要稠密的深度度支持图像反投影为点云，双目的话需要立体匹配获得视差图，单目需要SfM估计深度。或者考虑使用硬件带立体匹配的双目摄像头，比如小觅。

**Comment by runwithyourheart** [comment]
> 第一个数组不对齐的问题主要出现在固定维度Eigen数组为自定义类中成员变量，或者为标准库容器/智能指针模板元素等情况，具体情况见https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html
> 
> 第二个问题，理论上是可行的，但是实现不太容易，两者都需要稠密的深度度支持图像反投影为点云，双目的话需要立体匹配获得视差图，单目需要SfM估计深度。或者考虑使用硬件带立体匹配的双目摄像头，比如小觅。

好的，谢谢解答！！！
